version: '3'
services:
  mysql7:
    image: mysql:5.7.26
    container_name: mysql7
    hostname: mysql7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - 49156:3306
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    volumes:
      - ./sql:/sql
      - ./data:/var/lib/mysql